// landing.js - public landing page
// Loaded by /src/pages/index.html.
const ro = new IntersectionObserver((entries) => {
  entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('in'); });
}, { threshold: 0.1 });
document.querySelectorAll('.reveal').forEach(el => ro.observe(el));

function toggleFaq(btn) {
  const item = btn.closest('.faq-item');
  const isOpen = item.classList.contains('open');
  document.querySelectorAll('.faq-item.open').forEach(i => i.classList.remove('open'));
  if (!isOpen) item.classList.add('open');
}

let dropdownCloseTimer;
const toolsDropdown = document.getElementById('toolsDropdown');
function toggleToolsDropdown() { toolsDropdown.classList.toggle('open'); clearTimeout(dropdownCloseTimer); }
toolsDropdown.addEventListener('mouseenter', () => { clearTimeout(dropdownCloseTimer); toolsDropdown.classList.add('open'); });
toolsDropdown.addEventListener('mouseleave', () => { dropdownCloseTimer = setTimeout(() => { toolsDropdown.classList.remove('open'); }, 150); });
document.addEventListener('click', function(e) { if (!toolsDropdown.contains(e.target)) { clearTimeout(dropdownCloseTimer); toolsDropdown.classList.remove('open'); } });

function toggleMobileNav() { document.getElementById('mobileNav').classList.toggle('open'); document.getElementById('navHamburger').classList.toggle('open'); }
function closeMobileNav() { document.getElementById('mobileNav').classList.remove('open'); document.getElementById('navHamburger').classList.remove('open'); }
window.addEventListener('scroll', () => { if (document.getElementById('mobileNav').classList.contains('open')) closeMobileNav(); }, { passive: true });

const CALC_KEY='tradeCalcDefaults_v4';
let cAsset='crypto',cRiskMode='pct',cSlMode='price',cTpMode='price',fRiskMode='pct',fSlMode='pips',fTpMode='pips';
const CURRENCY_SYMBOLS={USD:'$',EUR:'€',GBP:'£',JPY:'¥',CHF:'Fr',AUD:'A$',CAD:'C$',NZD:'NZ$'};
const CONTRACT_SIZE=100000;
const APPROX_RATES={USD:1,EUR:1.08,GBP:1.27,JPY:0.0067,CHF:1.12,AUD:0.65,CAD:0.74,NZD:0.60};
function _getPipSize(pair){return pair.includes('JPY')?0.01:0.0001;}
function _getLotLabel(lots){if(lots>=0.9)return 'Standard lot'+(lots>=1.9?'s':'');if(lots>=0.09)return 'Mini lot'+(lots>=0.19?'s':'');return 'Micro lot'+(lots>=0.019?'s':'');}
function _getPipValuePerLot(pair,acctCcy,entryPrice){const pipSize=_getPipSize(pair);const pipValueInQuote=pipSize*CONTRACT_SIZE;let base,quote;const specials={XAUUSD:['XAU','USD'],XAGUSD:['XAG','USD'],US30:['US30','USD'],NAS100:['NAS100','USD']};if(specials[pair]){[base,quote]=specials[pair];}else{base=pair.slice(0,3);quote=pair.slice(3,6);}if(quote===acctCcy)return pipValueInQuote;if(base===acctCcy&&entryPrice>0)return pipValueInQuote/entryPrice;const quoteToUSD=APPROX_RATES[quote]||1;const acctToUSD=APPROX_RATES[acctCcy]||1;return pipValueInQuote*(quoteToUSD/acctToUSD);}
function _fmtMoney(n,ccy='USD',d=2){if(n===null||n===undefined||isNaN(n))return'—';const sym=CURRENCY_SYMBOLS[ccy]||ccy+' ';return sym+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});}
function _fmtUSD(n,d=2){return _fmtMoney(n,'USD',d);}
function _fmt(n,d=2){if(n===null||n===undefined||isNaN(n))return'—';return n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});}
function _sv(id,v){const e=document.getElementById(id);if(e)e.textContent=v;}
function _rrColor(rr){if(rr>=3)return'#00c896';if(rr>=2)return _lerpHex('#f59e0b','#00c896',rr-2);if(rr>=1)return _lerpHex('#ff4f6a','#f59e0b',rr-1);return'#ff4f6a';}
function _lerpHex(a,b,t){const ah=parseInt(a.slice(1),16),bh=parseInt(b.slice(1),16);const[ar,ag,ab_]=[(ah>>16)&0xff,(ah>>8)&0xff,ah&0xff];const[br,bg,bb]=[(bh>>16)&0xff,(bh>>8)&0xff,bh&0xff];const r=Math.round(ar+(br-ar)*t),g=Math.round(ag+(bg-ag)*t),b2=Math.round(ab_+(bb-ab_)*t);return'#'+[r,g,b2].map(x=>x.toString(16).padStart(2,'0')).join('');}
function _updateRR(rr){const elem=document.getElementById('cRrSection');if(!elem)return;if(rr===null||isNaN(rr)||rr<=0){elem.style.display='none';return;}elem.style.display='block';const col=_rrColor(rr),rrEl=document.getElementById('cRrVal');rrEl.textContent='1 : '+_fmt(rr,2);rrEl.style.color=col;const fill=document.getElementById('cRrFill');fill.style.width=Math.min((rr/3)*100,100)+'%';fill.style.background=rr>=3?'#00c896':`linear-gradient(to right, #ff4f6a, ${_rrColor(rr)})`;}
function cSetAsset(t){cAsset=t;['cBtnCrypto','cBtnForex','cryptoInputs','forexInputs','cCryptoResults','cForexResults'].forEach(id=>{const e=document.getElementById(id);if(!e)return;if(id.includes('Crypto'))e.classList?.toggle('active',t==='crypto');else if(id.includes('Forex'))e.classList?.toggle('active',t==='forex');else if(id==='cryptoInputs')e.style.display=t==='crypto'?'':'none';else if(id==='forexInputs')e.style.display=t==='forex'?'':'none';else if(id==='cCryptoResults')e.style.display=t==='crypto'?'':'none';else if(id==='cForexResults')e.style.display=t==='forex'?'':'none';});const acctCcy=document.getElementById('cAcctCurrency')?.value||'USD';const pre=document.getElementById('fBalancePre');if(pre)pre.textContent=CURRENCY_SYMBOLS[acctCcy]||'$';cCalc();}
function cSetRiskMode(m){cRiskMode=m;['cRiskPctBtn','cRiskUsdBtn'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Pct')?m==='pct':m==='usd'));const suf=document.getElementById('cRiskSuf');if(suf)suf.textContent=m==='pct'?'%':'$';cCalc();}
function cSetSlMode(m){cSlMode=m;['cSlPriceBtn','cSlPctBtn'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Price')?m==='price':m==='pct'));document.getElementById('cSlPriceWrap').style.display=m==='price'?'':'none';document.getElementById('cSlPctWrap').style.display=m==='pct'?'':'none';cCalc();}
function cSetTpMode(m){cTpMode=m;['cTpPriceBtn','cTpPctBtn'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Price')?m==='price':m==='pct'));document.getElementById('cTpPriceWrap').style.display=m==='price'?'':'none';document.getElementById('cTpPctWrap').style.display=m==='pct'?'':'none';cCalc();}
function fSetRiskMode(m){fRiskMode=m;['fRiskPctBtn','fRiskUsdBtn'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Pct')?m==='pct':m==='usd'));const suf=document.getElementById('fRiskSuf');if(suf)suf.textContent=m==='pct'?'%':(CURRENCY_SYMBOLS[document.getElementById('cAcctCurrency')?.value||'USD']||'$');cCalc();}
function fSetSlMode(m){fSlMode=m;['fSlPipsBtn','fSlPriceBtn2'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Pips')?m==='pips':m==='price'));document.getElementById('fSlPipsWrap').style.display=m==='pips'?'':'none';document.getElementById('fSlPriceWrap2').style.display=m==='price'?'':'none';cCalc();}
function fSetTpMode(m){fTpMode=m;['fTpPipsBtn','fTpPriceBtn2'].forEach(id=>document.getElementById(id)?.classList.toggle('active',id.includes('Pips')?m==='pips':m==='price'));document.getElementById('fTpPipsWrap').style.display=m==='pips'?'':'none';document.getElementById('fTpPriceWrap2').style.display=m==='price'?'':'none';cCalc();}
function cLoadDefaults(){try{const d=JSON.parse(localStorage.getItem(CALC_KEY));if(!d)return;if(d.capital)document.getElementById('cCapital').value=d.capital;if(d.riskVal)document.getElementById('cRiskVal').value=d.riskVal;if(d.riskMode)cSetRiskMode(d.riskMode);if(d.leverage)document.getElementById('cLeverage').value=d.leverage;if(d.asset)cSetAsset(d.asset);}catch(e){}}
function cSaveDefault(){const d={capital:document.getElementById('cCapital').value,riskVal:document.getElementById('cRiskVal').value,riskMode:cRiskMode,leverage:document.getElementById('cLeverage').value,asset:cAsset};localStorage.setItem(CALC_KEY,JSON.stringify(d));const btn=document.getElementById('cBtnSetDef'),fb=document.getElementById('cSaveFeedback');btn.classList.add('saved');fb.classList.add('show');setTimeout(()=>{btn.classList.remove('saved');fb.classList.remove('show');},2000);}
function cCalc(){if(cAsset==='crypto')_calcCrypto();else _calcForex();}
function _calcCrypto(){const capital=parseFloat(document.getElementById('cCapital').value),riskVal=parseFloat(document.getElementById('cRiskVal').value),entry=parseFloat(document.getElementById('cEntry').value),leverage=Math.max(1,parseFloat(document.getElementById('cLeverage').value)||1);_sv('cLevDisplay',leverage+'×');let riskAmt=null;if(!isNaN(capital)&&capital>0&&!isNaN(riskVal)&&riskVal>0)riskAmt=cRiskMode==='pct'?capital*(riskVal/100):riskVal;let slDist=null,slPct=null;if(!isNaN(entry)&&entry>0){if(cSlMode==='price'){const slP=parseFloat(document.getElementById('cSLPrice').value);if(!isNaN(slP)&&slP>0&&slP!==entry){slDist=Math.abs(entry-slP);slPct=(slDist/entry)*100;}}else{const sp=parseFloat(document.getElementById('cSLPct').value);if(!isNaN(sp)&&sp>0){slPct=sp;slDist=entry*(sp/100);}}}let tpDist=null,tpPct=null;if(!isNaN(entry)&&entry>0){if(cTpMode==='price'){const tpP=parseFloat(document.getElementById('cTPPrice').value);if(!isNaN(tpP)&&tpP>0&&tpP!==entry){tpDist=Math.abs(tpP-entry);tpPct=(tpDist/entry)*100;}}else{const tp=parseFloat(document.getElementById('cTPPct').value);if(!isNaN(tp)&&tp>0){tpPct=tp;tpDist=entry*(tp/100);}}}if(riskAmt!==null&&slDist!==null&&slDist>0){const posSize=riskAmt/slDist,posVal=posSize*entry,margin=posVal/leverage,profit=tpDist!==null?posSize*tpDist:null,rr=profit!==null?profit/riskAmt:null;_sv('cOutRisk',_fmtUSD(riskAmt));const riskSubParts=[];if(cRiskMode==='pct')riskSubParts.push(riskVal.toFixed(2)+'% of capital');else riskSubParts.push('fixed risk');if(slPct)riskSubParts.push('SL '+slPct.toFixed(3)+'% away');_sv('cOutRiskSub',riskSubParts.join(' · '));if(profit!==null){document.getElementById('cProfitCard').style.opacity='1';_sv('cOutProfit',_fmtUSD(profit));_sv('cOutProfitSub',tpPct?'TP '+tpPct.toFixed(3)+'% from entry':'if TP hit');}else{document.getElementById('cProfitCard').style.opacity='.35';_sv('cOutProfit','—');_sv('cOutProfitSub','set a take profit to calculate');}_sv('cOutMargin',_fmtUSD(margin));if(leverage>1){_sv('cOutMarginSub',`Position: ${_fmtUSD(posVal)} · ${leverage}× leverage`);document.getElementById('cLevNote').style.display='block';_sv('cLevNoteX',leverage+'×');_sv('cLevNotePos',_fmtUSD(posVal));_sv('cLevNoteMargin',_fmtUSD(margin));}else{_sv('cOutMarginSub',`Full position: ${_fmtUSD(posVal)}`);document.getElementById('cLevNote').style.display='none';}_updateRR(rr);}else{_cryptoClear();}}
function _cryptoClear(){_sv('cOutRisk','0');_sv('cOutRiskSub','if stop loss is hit');_sv('cOutProfit','0');_sv('cOutProfitSub','set a take profit to calculate');_sv('cOutMargin','0');_sv('cOutMarginSub','enter trade details to calculate');document.getElementById('cProfitCard').style.opacity='.35';document.getElementById('cLevNote').style.display='none';_sv('cLevDisplay',(parseFloat(document.getElementById('cLeverage').value)||1)+'×');_updateRR(null);}
function _calcForex(){const pair=document.getElementById('cPair').value||'EURUSD',acctCcy=document.getElementById('cAcctCurrency').value||'USD',balance=parseFloat(document.getElementById('cFBalance').value),riskInput=parseFloat(document.getElementById('cFRisk').value),entryRaw=parseFloat(document.getElementById('cFEntry').value),entry=!isNaN(entryRaw)&&entryRaw>0?entryRaw:0,pre=document.getElementById('fBalancePre');if(pre)pre.textContent=CURRENCY_SYMBOLS[acctCcy]||'$';if(isNaN(balance)||balance<=0||isNaN(riskInput)||riskInput<=0){_forexClear();return;}const riskAmt=fRiskMode==='pct'?balance*(riskInput/100):riskInput,pipSize=_getPipSize(pair);let slPips=null;if(fSlMode==='pips'){const p=parseFloat(document.getElementById('cFSLPips').value);if(!isNaN(p)&&p>0)slPips=p;}else{const slPrice=parseFloat(document.getElementById('cFSLPrice').value);if(!isNaN(slPrice)&&slPrice>0&&entry>0&&slPrice!==entry)slPips=Math.abs(entry-slPrice)/pipSize;}let tpPips=null;if(fTpMode==='pips'){const p=parseFloat(document.getElementById('cFTPPips').value);if(!isNaN(p)&&p>0)tpPips=p;}else{const tpPrice=parseFloat(document.getElementById('cFTPPrice').value);if(!isNaN(tpPrice)&&tpPrice>0&&entry>0&&tpPrice!==entry)tpPips=Math.abs(tpPrice-entry)/pipSize;}if(slPips===null||slPips<=0){_forexClear();return;}const pipValPerLot=_getPipValuePerLot(pair,acctCcy,entry),lots=riskAmt/(slPips*pipValPerLot),units=lots*CONTRACT_SIZE,moneyAtRisk=lots*slPips*pipValPerLot;let tpProfit=null,rr=null;if(tpPips!==null&&tpPips>0){tpProfit=lots*tpPips*pipValPerLot;rr=tpPips/slPips;}const pipValTotal=lots*pipValPerLot,sym=CURRENCY_SYMBOLS[acctCcy]||'$',fmtA=(n,d=2)=>n===null||isNaN(n)?'—':sym+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});_sv('fOutRiskAmt',fmtA(moneyAtRisk));_sv('fOutRiskPct',fRiskMode==='pct'?riskInput.toFixed(2)+'% of balance':'fixed risk');const lotsRounded=Math.round(lots*100)/100;_sv('fOutLots',_fmt(lotsRounded,lotsRounded<0.01?4:lotsRounded<0.1?3:2));_sv('fOutLotType',_getLotLabel(lotsRounded));_sv('fOutUnits',Math.round(units).toLocaleString('en-US'));_sv('fOutPipVal',fmtA(pipValPerLot,pipValPerLot<1?3:2));_sv('fOutPipValSub','per pip · 1 std lot');const slInfoEl=document.getElementById('fSlInfo');if(slInfoEl)slInfoEl.style.display='';_sv('fOutSlPips',_fmt(slPips,slPips%1===0?0:1));_sv('fOutPipSize',pipSize===0.0001?'0.0001':'0.01');_sv('fOutContract',CONTRACT_SIZE.toLocaleString('en-US'));if(tpProfit!==null){document.getElementById('fPnlSec').style.display='';_sv('fOutProfit',fmtA(tpProfit));_sv('fOutProfitPips',_fmt(tpPips,tpPips%1===0?0:1)+' pips');_sv('fOutPipValTotal',fmtA(pipValTotal,pipValTotal<1?3:2));}else{document.getElementById('fPnlSec').style.display='none';}_updateRR(rr);}
function _forexClear(){['fOutRiskAmt','fOutRiskPct','fOutLots','fOutLotType','fOutUnits','fOutPipVal','fOutPipValSub','fOutSlPips','fOutPipSize'].forEach(k=>_sv(k,'0'));const slInfoEl=document.getElementById('fSlInfo');if(slInfoEl)slInfoEl.style.display='none';document.getElementById('fPnlSec').style.display='none';_updateRR(null);}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('cAcctCurrency')?.addEventListener('change',()=>{const acctCcy=document.getElementById('cAcctCurrency').value,pre=document.getElementById('fBalancePre');if(pre)pre.textContent=CURRENCY_SYMBOLS[acctCcy]||'$';if(fRiskMode==='usd'){const suf=document.getElementById('fRiskSuf');if(suf)suf.textContent=CURRENCY_SYMBOLS[acctCcy]||'$';}cCalc();});});

const PAGES={calculator:{title:'Free Crypto & Forex Risk Calculator | TradingGrove',file:'pages/calculator.html'},'crypto-calculator':{title:'Free Crypto Position Size Calculator | TradingGrove',file:'pages/crypto-calculator.html'}};
async function loadPage(pageName){const page=PAGES[pageName];if(!page){showHomePage();return;}try{const response=await fetch(page.file);if(!response.ok)throw new Error('Page not found');const html=await response.text();document.getElementById('pageTitle').textContent=page.title;document.getElementById('pageContent').querySelector('.pw').innerHTML=html;document.getElementById('homePage').style.display='none';document.getElementById('pageContent').style.display='block';if(pageName==='crypto-calculator'){cLoadDefaults();cCalc();}else if(pageName==='calculator'){cLoadDefaults();cCalc();if(window.location.hash.includes('forex'))setTimeout(()=>cSetAsset('forex'),100);}window.scrollTo(0,0);}catch(error){console.error('Error loading page:',error);showHomePage();}}
function showHomePage(){document.getElementById('pageTitle').textContent='TradingGrove | A trading journal that helps you understand your own trading.';document.getElementById('homePage').style.display='block';document.getElementById('pageContent').style.display='none';window.scrollTo(0,0);}
window.addEventListener('hashchange',()=>{
  const hash=window.location.hash.slice(1);
  const pageName=hash.split('#')[0];
  if(pageName&&PAGES[pageName]){loadPage(pageName);return;}
  // Not a calculator sub-page hash (e.g. an in-page section anchor like #features).
  // Only reset to the home view when actually leaving a sub-page — otherwise let
  // the browser's native smooth-scroll handle the anchor without forcing scrollTo(0,0).
  const onSubPage=document.getElementById('pageContent').style.display==='block';
  if(onSubPage)showHomePage();
});
window.addEventListener('load',()=>{const hash=window.location.hash.slice(1);const pageName=hash.split('#')[0];if(pageName&&PAGES[pageName])loadPage(pageName);});

// Inline handlers in HTML call these by global name.
Object.assign(window, { closeMobileNav, toggleFaq, toggleMobileNav, toggleToolsDropdown });